"""License inventory of the Python packages bundled in a release.

Run with the bundled Python (macos/build.sh does this):

    python license_report.py <output.md>

Writes one line per installed package (name, version, license) and exits with an
error if a package is GPL or AGPL licensed. LGPL is allowed: those packages stay
separate, replaceable files. Packages whose license can't be read are listed as
"unknown" and should be checked by hand.
"""

from __future__ import annotations

import re
import sys
from importlib import metadata
from pathlib import Path

LGPL = re.compile(r"\bLGPL|Lesser General Public", re.I)
GPL = re.compile(r"\b(A?GPL)|General Public License", re.I)


def license_of(dist: metadata.Distribution) -> str:
    meta = dist.metadata
    expression = meta.get("License-Expression")
    if expression:
        return expression.strip()
    classifiers = [c.split("::")[-1].strip() for c in meta.get_all("Classifier") or [] if c.startswith("License ::")]
    classifiers = [c for c in classifiers if c != "OSI Approved"]
    if classifiers:
        return "; ".join(classifiers)
    text = (meta.get("License") or "").strip().splitlines()
    return text[0][:80] if text else "unknown"


def is_gpl(license_text: str) -> bool:
    """GPL or AGPL anywhere, after removing the LGPL mentions."""
    return bool(GPL.search(LGPL.sub("", license_text)))


def main() -> int:
    out = Path(sys.argv[1])
    rows, problems = [], []
    for dist in sorted(metadata.distributions(), key=lambda d: (d.metadata["Name"] or "").lower()):
        name, version = dist.metadata["Name"], dist.version
        lic = license_of(dist)
        rows.append(f"| {name} | {version} | {lic} |")
        if is_gpl(lic):
            problems.append(f"{name} {version}: {lic}")

    out.write_text(
        "# Python packages in this build\n\n"
        "Generated by `macos/license_report.py` when this release was built.\n\n"
        "| Package | Version | License |\n|---|---|---|\n" + "\n".join(rows) + "\n",
        encoding="utf-8",
    )
    print(f"{len(rows)} packages listed in {out}")
    if problems:
        print("GPL licensed packages must not be bundled:\n  " + "\n  ".join(problems), file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
